#!/usr/bin/python

# pluo, Apr 1, 2013
# PATH=$PATH:/home/dataproc/bi/lib/python # add python lib to path
# csv_to_hive --hive_db='staging' --hive_table='fact_property_view_partition' --hive_partition="date_int=20130428" /tmp/fact_property_view.csv

import legoo
import sys
from optparse import OptionParser

def main():
  parser = OptionParser()
  parser.add_option("--hive_node", dest="hive_node",
                    help="OPTIONAL: target hive node. default: [namenode1]", default='namenode1')
  parser.add_option("--hive_port", dest="hive_port",
                    help="OPTIONAL: target hive port number. default: 10000", default='10000')
  parser.add_option("--hive_db", dest="hive_db",
                    help="OPTIONAL: target hive db. default: [staging]", default='staging')
  parser.add_option("--hive_table", dest="hive_table",
                    help="OPTIONAL: hive table name. default: created from csv file name")
  parser.add_option("--hive_partition", dest="hive_partition",
                    help="partition name i.e. date_int=20130428")
  parser.add_option("--hive_create_table", dest="hive_create_table",
                    help="OPTIONAL: CREATE_TABLE flag for hive table DDL. default: [Y]", default='N')
  parser.add_option("--hive_overwrite", dest="hive_overwrite",
                    help="OPTIONAL: OVERWRITE flag for hive table loading. default: [Y]", default='Y')
  parser.add_option("--csv_header", dest="csv_header",
                    help="OPTIONAL: csv_header flag csv file default: [Y]", default='Y')

  parser.add_option("--remove_carriage_return", dest="remove_carriage_return",
                    help="OPTIONAL: remove carriage return from mysql source table. default: [N]", default='N')
  parser.add_option("--csv_delimiter", dest="csv_delimiter", help="delimiter for csv file, default: [tab]", default='tab')
  parser.add_option("--debug", dest="debug", help="debug flag [Y|N], default: [N]", default='N')
  (options, args) = parser.parse_args()

  for csv_file in args:
      legoo.csv_to_hive(  hive_node              = options.hive_node, \
                        hive_port              = options.hive_port, \
                        hive_db                = options.hive_db, \
                        hive_create_table      = options.hive_create_table, \
                        hive_table             = options.hive_table, \
                        hive_partition         = options.hive_partition, \
                        hive_overwrite         = options.hive_overwrite, \
                        csv_file               = csv_file, \
                        csv_header             = options.csv_header, \
                        csv_delimiter          = options.csv_delimiter, \
                        remove_carriage_return = options.remove_carriage_return, \
                        debug                  = options.debug
                    )
  # pass

if __name__ == '__main__':
  main()

